function [] = fbmod_multilevel_competitive_selection()

dbstop if error; close all;
h = fbmod_helpers;

fs = [30 24 16 12];

%% ------- multilevel competitive queuing model of the utterance:
%a dog and a cat chased a monkey (each row is a pword)

% utterance = {...
%     {{'V_1'} {'C_2' 'V_2' 'R2' 'c_2' 'r2'}}...
%     {{'V_3' 'c_31' 'c_32' 'r31' 'r32'} {'V_4'} {'C_5' 'V_5' 'R5' 'c_5' 'r5'}}...
%     {{'C_6' 'V_2' 'R6' 'c_61' 'c_62' 'r61' 'r62'}}...
%     {{'C_7' 'V_7' 'R7'} {'C_8' 'V_8' 'R8' 'c_8' 'r8'} {'C_9' 'V_9' 'R9'}}...
%     };

utterance = {...
    {{'V_1'} {'C_2' 'V_2' 'c_2'}}...
    {{'V_3' 'c_{31}' 'c_{32}'} {'V_4'} {'C_5' 'V_5' 'c_5'}}...
    {{'C_6' 'V_6' 'c_{61}' 'c_{62}'}}...
    {{'C_7' 'V_7'} {'C_8' 'V_8' 'c_8'} {'C_9' 'V_9'}}...
    };

% utterance = {...
%     {{'C_1' 'V_1' 'R_1'} {'C_2' 'V_2' 'R_2'}}...
%     {{'C_3' 'V_3' 'R_3'} {'C_4' 'V_4' 'R_4'} {'C_5' 'V_5' 'R_5'}}...
%     {{'C_6' 'V_6' 'R_6'} }...
%     {{'C_7' 'V_7' 'R_7'} {'C_8' 'V_8' 'R_8'} {'C_9' 'V_9' 'R_9'}}...
%     };

%%

[M,U,P] = fbmod_gen_utterance_model('standard',utterance,'dur',4.5);

M.color = viridis(M.Ng)';

M = fbmod_run_models(M);

%%
schema_params = {...
    'radius',[1/3 1/8 1/5],...
    'fontsize',fs([2 4 3]),...
    'labeltype',{'full' 'minimal' 'full'}};

M = fbmod_prep_schema(M,schema_params{:});

M.PHI_XX = []; M.F_XX = [];

save([h.sim_dir mfilename '.mat'],'M','U','P');


end
